version: '3.8'


networks:
  archery:
    driver: bridge


services:
  backend:
    image: archery/backend
    container_name: backend
    env_file:
      - .env
    ports:
      - 3333:3333
    networks:
      - archery
  frontend:
    image: archery/frontend
    container_name: frontend
    environment:
      APP_API_URL: http://localhost:3333
    ports:
      - 3000:80
    networks:
      - archery

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    networks:
      - archery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
