on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Set short git comme SHA
        id: extract-version
        run: |
          echo ${{ github.sha }} 
          VERSION=$(git rev-parse --short ${{ github.sha }})
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Confirm git comme SHA output
        run: echo ${{ steps.extract-version.outputs.VERSION }}
  test:
    runs-on: ubuntu-latest
    needs: [extract-version]
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: backend_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm run test
          
  build:
    needs: [extract-version, test]
    uses: archery-progress/infrastructure/.github/workflows/build-and-push.yaml@main
    with:
      registry: ghcr.io
      ref: main
      push: false
      repository: archery-progress/backend
      tag: ${{ needs.extract-version.outputs.version }}
      registry_username: ${{ github.actor }}

    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
